### PR TITLE
Fix #40 : Fix by setting project's default encoding as UTF-8

### LINKED ISSUE #40: BUG : Default encoding of each users are different
**Describe the bug**
The project's default encoding is not specified. Because of this, some users run programs as UTF-8 and some as MS949. Thus you will see garbled characters when chatting. 

**To Reproduce**
1. Type chat message.
2. Send the message by pressing the Enter button.
3. Chat message is shown garbled.

**Expected behavior**
The message you sent is shown to the chat screen intactly.

### PR DESCRIPTION
**Pull request by pllap**
#40 issue was about the received chat was shown garbled because the default encoding was not set. Fixed this bug by adding a line that sets default encoding of the project to the first line of main().

### CODE REVIEW

File: src/com/thunder_cut/netio/Connection.java [hunk 1]
```diff
@@ -67,7 +68,8 @@ public static void createConnection(String address, int port) {
         connectionModule.receivingExecutorService = Executors.newSingleThreadExecutor();
         startReceiving();
 
-        send(ChatCommands.SET_NAME + getNickname());
+        setNickname("user" + Integer.toString(ThreadLocalRandom.current().nextInt(65536)));
```
Comment (Kasania) [inline src/com/thunder_cut/netio/Connection.java]: I think, this method have to move to initialize method.

**Review by Kasania — CHANGES_REQUESTED** [review]

**Review by Kasania — APPROVED** [review]
